onboarding:
  seen:
    profile_build_offered: true
_config_version: 37
platforms:
  telegram:
    enabled: true
    home_channel:
      platform: telegram
      chat_id: '6874843931'
      name: Azas Crack
      thread_id: '38372'
      user_id: '6874843931'
agent: {}
model:
  default: gemma4:31b
